create readme
aHub-Tech/pulapirata pull request #2
Opened 2021-07-22 00:27 UTC by vcwild

- Criado arquivo readme
- Criados assets para referência no arquivo readme

Falta:
- Decidir a licença utilizada no projeto e preencher ao final do arquivo README

closes #1

2021-07-22 00:34 UTC, vcwild commented
Observei que está faltando um arquivo de requirements para colocarmos os requerimentos do projeto, o requirements do projeto não está citado no README, afetando a replicação do projeto por outros contribuidores

2021-07-22 02:33 UTC, vcwild commented
Conforme conversado será criado uma categoria ## Requirements no README apontando que o projeto é vanilla e não utiliza pacotes de importação.

2021-07-22 13:43 UTC, vcwild commented
Atualizado README com:
- Cabeçalho com badges
- Citação a licença MIT
- Requirements de projeto

2021-07-24 00:33 UTC, adelsonguimaraes commented on README.md
> +  <img src=".github/database_uml.jpg" width="350px" />
1. Aumentar o width da imagem de uml 450px
2. Alinhar ao centro

2021-07-24 00:35 UTC, adelsonguimaraes requested changes
Correções apontadas no código.

2021-07-24 00:46 UTC, DevRadhy commented on README.md
> +  <img src=".github/database_uml.jpg" width="350px" />
correção feita no **PR #3**

2021-07-24 00:54 UTC, adelsonguimaraes approved these changes
ok. 😎

2021-07-24 01:13 UTC, merged